all	:
	g++ -std=c++11 main.cpp -I../../include -I$(CDF_LIBRARY_PATH)/include -L$(CDF_LIBRARY_PATH)/lib -L../.. -lCLDIA -lcdf -lz -O3

backup	:
	g++ -std=c++11 backup.cpp -I../../include -I$(CDF_LIBRARY_PATH)/include -L$(CDF_LIBRARY_PATH)/lib -L../.. -lCLDIA -lcdf -lz -O3
