#!/usr/bin/perl
use POSIX;
use Math::Trig;

if(@ARGV < 1){
    print STDERR "Usage : wdf-graph [input_file]\n";
    exit(0);
}

$input_file    = $ARGV[0];
$eps_file      = "$input_file.eps";
$pdf_file      = "$input_file.pdf";
$grd_file      = "$input_file.grd";
$cpt_file      = "$input_file.cpt";
$grid_spacing  = 1.01;
$color_palette = "jet";
$min_intensity = 0.0;
$a4_width      = 21.0;
$a4_height     = 29.7;
$diameter      =  5.0;
$distance      = $diameter / 2.0 + 1.0;

`rm gmt.conf`;

`gmt surface ${input_file} -G${grd_file} -R0/360/-90/+90 -I${grid_spacing} -T0.25`;

if(@ARGV != 1){
    $max  = $ARGV[1] + 0;
}else{
    @str  = `gmt grdinfo ${grd_file} -C`;
    @list = split(/\t/,$str[0]);
    $max  = $list[6] + 0;
    if($max == 0.0){
       $max  = 0.9;
    }
}

$eff  = $max;
$sft  =  1.0;

while($eff >= 10.0){
      $eff /= 10.0;
      $sft *= 10.0;
}

while($eff <   1.0){
      $eff *= 10.0;
      $sft /= 10.0;
}

$z_spacing     = ($eff >= 5.0) ? $sft       : 
                 ($eff >= 2.0) ? $sft * 0.5 :  
                                 $sft * 0.2 ;
$z_spacing    *=  2.0;
$max_intensity = ceil($max / $z_spacing) *  $z_spacing;

$color_spacing = $max_intensity / 1000.0;

`gmt makecpt -C${color_palette} -T${min_intensity}/${max_intensity}/${color_spacing} -D > ${cpt_file}`;

`gmt gmtset PS_MEDIA a4`;
`gmt gmtset FONT_ANNOT_PRIMARY 10p,Times-Roman,black`;
`gmt gmtset FONT_ANNOT_SECONDARY 10p,Times-Roman,black`;
`gmt gmtset FONT_LABEL 10p,Times-Roman,black`;
`gmt gmtset FONT_LOGO 10p,Times-Roman,black`;
`gmt gmtset FONT_TITLE 10p,Times-Roman,black`;

$origin_x = $a4_width  / 2.0 - $diameter / 2.0 - $distance;
$origin_y = $a4_height / 2.0 - $diameter / 2.0;

`gmt gmtset MAP_FRAME_PEN 0.5p,0/0/100`;
`gmt gmtset MAP_GRID_PEN_PRIMARY 0.1p,150/150/255,.-`;
`gmt grdimage ${grd_file} -R0/360/-90/+90 -JG-90/+89.99/${diameter}c -Bg30/g10 -C${cpt_file} -Xa${origin_x}c -Ya${origin_y}c -P -K > ${eps_file}`;

$str = "gmt pstext -R0/360/0/1 -JP${diameter}c -F+f10p,Times-Roman,black+jCM -N -Xa${origin_x}c -Ya${origin_y}c -P -K -O << EOF >> ${eps_file}\n";
$str.= "  0    1.2    0@~\260@~\n";
$str.= " 30    1.2   30@~\260@~\n";
$str.= " 60    1.2   60@~\260@~\n";
$str.= " 90    1.2   90@~\260@~\n";
$str.= "120    1.2  120@~\260@~\n";
$str.= "150    1.2  150@~\260@~\n";
$str.= "180    1.2  180@~\260@~\n";
$str.= "210    1.2  210@~\260@~\n";
$str.= "240    1.2  240@~\260@~\n";
$str.= "270    1.2  270@~\260@~\n";
$str.= "300    1.2  300@~\260@~\n";
$str.= "330    1.2  330@~\260@~\n";
$str.= " 90    1.4  Northern\n";
$str.= "EOF\n";

`$str`;

$origin_x = $a4_width  / 2.0 - $diameter / 2.0 + $distance;
$origin_y = $a4_height / 2.0 - $diameter / 2.0;

`gmt gmtset MAP_FRAME_PEN 0.5p,0/0/100`;
`gmt gmtset MAP_GRID_PEN_PRIMARY 0.1p,150/150/255,.-`;
`gmt grdimage ${grd_file} -R0/360/-90/90 -JG+90/-89.99/${diameter}c -Bg30/g10 -C${cpt_file} -Xa${origin_x}c -Ya${origin_y}c -P -K -O >> ${eps_file}`;

$str = "gmt pstext -R0/360/0/1 -JP${diameter}c -F+f10p,Times-Roman,black+jCM -N -Xa${origin_x}c -Ya${origin_y}c -P -K -O << EOF >> ${eps_file}\n";
$str.= "  0    1.2  180@~\260@~\n";
$str.= " 30    1.2  150@~\260@~\n";
$str.= " 60    1.2  120@~\260@~\n";
$str.= " 90    1.2   90@~\260@~\n";
$str.= "120    1.2   60@~\260@~\n";
$str.= "150    1.2   30@~\260@~\n";
$str.= "180    1.2    0@~\260@~\n";
$str.= "210    1.2  330@~\260@~\n";
$str.= "240    1.2  300@~\260@~\n";
$str.= "270    1.2  270@~\260@~\n";
$str.= "300    1.2  240@~\260@~\n";
$str.= "330    1.2  210@~\260@~\n";
$str.= " 90    1.4  Southern\n";
$str.= "EOF\n";

`$str`;

$origin_x = $a4_width  / 2.0;
$origin_y = $a4_height / 2.0 - $diameter / 2.0 - 1.0;

$scale_length = $diameter * 2.0 * 0.7;

`gmt gmtset MAP_FRAME_PEN 0.1p,black`;
`gmt gmtset MAP_GRID_PEN_PRIMARY 0.1p,black`;
`gmt psscale -D0c/0c/${scale_length}c/0.3ch -C${cpt_file} -Ba${z_spacing}g${z_spacing}:\"Power Density [J/m\@+3\@+]\": -Xa${origin_x}c -Ya${origin_y}c -P -O >> ${eps_file}`;

`gmt ps2raster ${eps_file} -A -Tf`;

`rm ${eps_file} ${grd_file} ${cpt_file} gmt.conf`;

`open -a Preview.app ${pdf_file}`
